/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPromptsRouteImport } from './routes/_authenticated/prompts'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedModelsRouteImport } from './routes/_authenticated/models'
import { Route as AuthenticatedMemoryRouteImport } from './routes/_authenticated/memory'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as AuthenticatedFilesRouteImport } from './routes/_authenticated/files'
import { Route as AuthenticatedFactoryRouteImport } from './routes/_authenticated/factory'
import { Route as AuthenticatedEvalsRouteImport } from './routes/_authenticated/evals'
import { Route as AuthenticatedDigestRouteImport } from './routes/_authenticated/digest'
import { Route as AuthenticatedCostRouteImport } from './routes/_authenticated/cost'
import { Route as AuthenticatedCaptureRouteImport } from './routes/_authenticated/capture'
import { Route as AuthenticatedAskRouteImport } from './routes/_authenticated/ask'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPromptsRoute = AuthenticatedPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModelsRoute = AuthenticatedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemoryRoute = AuthenticatedMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilesRoute = AuthenticatedFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFactoryRoute = AuthenticatedFactoryRouteImport.update({
  id: '/factory',
  path: '/factory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEvalsRoute = AuthenticatedEvalsRouteImport.update({
  id: '/evals',
  path: '/evals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDigestRoute = AuthenticatedDigestRouteImport.update({
  id: '/digest',
  path: '/digest',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCostRoute = AuthenticatedCostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaptureRoute = AuthenticatedCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAskRoute = AuthenticatedAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AuthenticatedAskRoute
  '/capture': typeof AuthenticatedCaptureRoute
  '/cost': typeof AuthenticatedCostRoute
  '/digest': typeof AuthenticatedDigestRoute
  '/evals': typeof AuthenticatedEvalsRoute
  '/factory': typeof AuthenticatedFactoryRoute
  '/files': typeof AuthenticatedFilesRoute
  '/health': typeof AuthenticatedHealthRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/models': typeof AuthenticatedModelsRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/prompts': typeof AuthenticatedPromptsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AuthenticatedAskRoute
  '/capture': typeof AuthenticatedCaptureRoute
  '/cost': typeof AuthenticatedCostRoute
  '/digest': typeof AuthenticatedDigestRoute
  '/evals': typeof AuthenticatedEvalsRoute
  '/factory': typeof AuthenticatedFactoryRoute
  '/files': typeof AuthenticatedFilesRoute
  '/health': typeof AuthenticatedHealthRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/models': typeof AuthenticatedModelsRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/prompts': typeof AuthenticatedPromptsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/ask': typeof AuthenticatedAskRoute
  '/_authenticated/capture': typeof AuthenticatedCaptureRoute
  '/_authenticated/cost': typeof AuthenticatedCostRoute
  '/_authenticated/digest': typeof AuthenticatedDigestRoute
  '/_authenticated/evals': typeof AuthenticatedEvalsRoute
  '/_authenticated/factory': typeof AuthenticatedFactoryRoute
  '/_authenticated/files': typeof AuthenticatedFilesRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/memory': typeof AuthenticatedMemoryRoute
  '/_authenticated/models': typeof AuthenticatedModelsRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/prompts': typeof AuthenticatedPromptsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/capture'
    | '/cost'
    | '/digest'
    | '/evals'
    | '/factory'
    | '/files'
    | '/health'
    | '/knowledge'
    | '/memory'
    | '/models'
    | '/overview'
    | '/prompts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/capture'
    | '/cost'
    | '/digest'
    | '/evals'
    | '/factory'
    | '/files'
    | '/health'
    | '/knowledge'
    | '/memory'
    | '/models'
    | '/overview'
    | '/prompts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/ask'
    | '/_authenticated/capture'
    | '/_authenticated/cost'
    | '/_authenticated/digest'
    | '/_authenticated/evals'
    | '/_authenticated/factory'
    | '/_authenticated/files'
    | '/_authenticated/health'
    | '/_authenticated/knowledge'
    | '/_authenticated/memory'
    | '/_authenticated/models'
    | '/_authenticated/overview'
    | '/_authenticated/prompts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/prompts': {
      id: '/_authenticated/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AuthenticatedPromptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/models': {
      id: '/_authenticated/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthenticatedModelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memory': {
      id: '/_authenticated/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AuthenticatedMemoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/files': {
      id: '/_authenticated/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AuthenticatedFilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/factory': {
      id: '/_authenticated/factory'
      path: '/factory'
      fullPath: '/factory'
      preLoaderRoute: typeof AuthenticatedFactoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evals': {
      id: '/_authenticated/evals'
      path: '/evals'
      fullPath: '/evals'
      preLoaderRoute: typeof AuthenticatedEvalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/digest': {
      id: '/_authenticated/digest'
      path: '/digest'
      fullPath: '/digest'
      preLoaderRoute: typeof AuthenticatedDigestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cost': {
      id: '/_authenticated/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof AuthenticatedCostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/capture': {
      id: '/_authenticated/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof AuthenticatedCaptureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ask': {
      id: '/_authenticated/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AuthenticatedAskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAskRoute: typeof AuthenticatedAskRoute
  AuthenticatedCaptureRoute: typeof AuthenticatedCaptureRoute
  AuthenticatedCostRoute: typeof AuthenticatedCostRoute
  AuthenticatedDigestRoute: typeof AuthenticatedDigestRoute
  AuthenticatedEvalsRoute: typeof AuthenticatedEvalsRoute
  AuthenticatedFactoryRoute: typeof AuthenticatedFactoryRoute
  AuthenticatedFilesRoute: typeof AuthenticatedFilesRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedMemoryRoute: typeof AuthenticatedMemoryRoute
  AuthenticatedModelsRoute: typeof AuthenticatedModelsRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedPromptsRoute: typeof AuthenticatedPromptsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAskRoute: AuthenticatedAskRoute,
  AuthenticatedCaptureRoute: AuthenticatedCaptureRoute,
  AuthenticatedCostRoute: AuthenticatedCostRoute,
  AuthenticatedDigestRoute: AuthenticatedDigestRoute,
  AuthenticatedEvalsRoute: AuthenticatedEvalsRoute,
  AuthenticatedFactoryRoute: AuthenticatedFactoryRoute,
  AuthenticatedFilesRoute: AuthenticatedFilesRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedMemoryRoute: AuthenticatedMemoryRoute,
  AuthenticatedModelsRoute: AuthenticatedModelsRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedPromptsRoute: AuthenticatedPromptsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
