/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProbeOverviewRouteImport } from './routes/probe-overview'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSystemRouteImport } from './routes/_authenticated/system'
import { Route as AuthenticatedSkillsRouteImport } from './routes/_authenticated/skills'
import { Route as AuthenticatedProposalsRouteImport } from './routes/_authenticated/proposals'
import { Route as AuthenticatedPromptsRouteImport } from './routes/_authenticated/prompts'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedModelsRouteImport } from './routes/_authenticated/models'
import { Route as AuthenticatedModelScannerRouteImport } from './routes/_authenticated/model-scanner'
import { Route as AuthenticatedMemoryRouteImport } from './routes/_authenticated/memory'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as AuthenticatedFilesRouteImport } from './routes/_authenticated/files'
import { Route as AuthenticatedFactoryRouteImport } from './routes/_authenticated/factory'
import { Route as AuthenticatedEvalsRouteImport } from './routes/_authenticated/evals'
import { Route as AuthenticatedDigestRouteImport } from './routes/_authenticated/digest'
import { Route as AuthenticatedCostRouteImport } from './routes/_authenticated/cost'
import { Route as AuthenticatedCaptureRouteImport } from './routes/_authenticated/capture'
import { Route as AuthenticatedBuildRouteImport } from './routes/_authenticated/build'
import { Route as AuthenticatedAskRouteImport } from './routes/_authenticated/ask'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const ProbeOverviewRoute = ProbeOverviewRouteImport.update({
  id: '/probe-overview',
  path: '/probe-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSystemRoute = AuthenticatedSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkillsRoute = AuthenticatedSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProposalsRoute = AuthenticatedProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromptsRoute = AuthenticatedPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModelsRoute = AuthenticatedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModelScannerRoute =
  AuthenticatedModelScannerRouteImport.update({
    id: '/model-scanner',
    path: '/model-scanner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMemoryRoute = AuthenticatedMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilesRoute = AuthenticatedFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFactoryRoute = AuthenticatedFactoryRouteImport.update({
  id: '/factory',
  path: '/factory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEvalsRoute = AuthenticatedEvalsRouteImport.update({
  id: '/evals',
  path: '/evals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDigestRoute = AuthenticatedDigestRouteImport.update({
  id: '/digest',
  path: '/digest',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCostRoute = AuthenticatedCostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaptureRoute = AuthenticatedCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuildRoute = AuthenticatedBuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAskRoute = AuthenticatedAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/probe-overview': typeof ProbeOverviewRoute
  '/ask': typeof AuthenticatedAskRoute
  '/build': typeof AuthenticatedBuildRoute
  '/capture': typeof AuthenticatedCaptureRoute
  '/cost': typeof AuthenticatedCostRoute
  '/digest': typeof AuthenticatedDigestRoute
  '/evals': typeof AuthenticatedEvalsRoute
  '/factory': typeof AuthenticatedFactoryRoute
  '/files': typeof AuthenticatedFilesRoute
  '/health': typeof AuthenticatedHealthRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/model-scanner': typeof AuthenticatedModelScannerRoute
  '/models': typeof AuthenticatedModelsRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/proposals': typeof AuthenticatedProposalsRoute
  '/skills': typeof AuthenticatedSkillsRoute
  '/system': typeof AuthenticatedSystemRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/probe-overview': typeof ProbeOverviewRoute
  '/ask': typeof AuthenticatedAskRoute
  '/build': typeof AuthenticatedBuildRoute
  '/capture': typeof AuthenticatedCaptureRoute
  '/cost': typeof AuthenticatedCostRoute
  '/digest': typeof AuthenticatedDigestRoute
  '/evals': typeof AuthenticatedEvalsRoute
  '/factory': typeof AuthenticatedFactoryRoute
  '/files': typeof AuthenticatedFilesRoute
  '/health': typeof AuthenticatedHealthRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/model-scanner': typeof AuthenticatedModelScannerRoute
  '/models': typeof AuthenticatedModelsRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/proposals': typeof AuthenticatedProposalsRoute
  '/skills': typeof AuthenticatedSkillsRoute
  '/system': typeof AuthenticatedSystemRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/probe-overview': typeof ProbeOverviewRoute
  '/_authenticated/ask': typeof AuthenticatedAskRoute
  '/_authenticated/build': typeof AuthenticatedBuildRoute
  '/_authenticated/capture': typeof AuthenticatedCaptureRoute
  '/_authenticated/cost': typeof AuthenticatedCostRoute
  '/_authenticated/digest': typeof AuthenticatedDigestRoute
  '/_authenticated/evals': typeof AuthenticatedEvalsRoute
  '/_authenticated/factory': typeof AuthenticatedFactoryRoute
  '/_authenticated/files': typeof AuthenticatedFilesRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/memory': typeof AuthenticatedMemoryRoute
  '/_authenticated/model-scanner': typeof AuthenticatedModelScannerRoute
  '/_authenticated/models': typeof AuthenticatedModelsRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/prompts': typeof AuthenticatedPromptsRoute
  '/_authenticated/proposals': typeof AuthenticatedProposalsRoute
  '/_authenticated/skills': typeof AuthenticatedSkillsRoute
  '/_authenticated/system': typeof AuthenticatedSystemRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/probe-overview'
    | '/ask'
    | '/build'
    | '/capture'
    | '/cost'
    | '/digest'
    | '/evals'
    | '/factory'
    | '/files'
    | '/health'
    | '/knowledge'
    | '/memory'
    | '/model-scanner'
    | '/models'
    | '/overview'
    | '/prompts'
    | '/proposals'
    | '/skills'
    | '/system'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/probe-overview'
    | '/ask'
    | '/build'
    | '/capture'
    | '/cost'
    | '/digest'
    | '/evals'
    | '/factory'
    | '/files'
    | '/health'
    | '/knowledge'
    | '/memory'
    | '/model-scanner'
    | '/models'
    | '/overview'
    | '/prompts'
    | '/proposals'
    | '/skills'
    | '/system'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/probe-overview'
    | '/_authenticated/ask'
    | '/_authenticated/build'
    | '/_authenticated/capture'
    | '/_authenticated/cost'
    | '/_authenticated/digest'
    | '/_authenticated/evals'
    | '/_authenticated/factory'
    | '/_authenticated/files'
    | '/_authenticated/health'
    | '/_authenticated/knowledge'
    | '/_authenticated/memory'
    | '/_authenticated/model-scanner'
    | '/_authenticated/models'
    | '/_authenticated/overview'
    | '/_authenticated/prompts'
    | '/_authenticated/proposals'
    | '/_authenticated/skills'
    | '/_authenticated/system'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ProbeOverviewRoute: typeof ProbeOverviewRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/probe-overview': {
      id: '/probe-overview'
      path: '/probe-overview'
      fullPath: '/probe-overview'
      preLoaderRoute: typeof ProbeOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/system': {
      id: '/_authenticated/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AuthenticatedSystemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skills': {
      id: '/_authenticated/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthenticatedSkillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals': {
      id: '/_authenticated/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof AuthenticatedProposalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prompts': {
      id: '/_authenticated/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AuthenticatedPromptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/models': {
      id: '/_authenticated/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthenticatedModelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/model-scanner': {
      id: '/_authenticated/model-scanner'
      path: '/model-scanner'
      fullPath: '/model-scanner'
      preLoaderRoute: typeof AuthenticatedModelScannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memory': {
      id: '/_authenticated/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AuthenticatedMemoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/files': {
      id: '/_authenticated/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AuthenticatedFilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/factory': {
      id: '/_authenticated/factory'
      path: '/factory'
      fullPath: '/factory'
      preLoaderRoute: typeof AuthenticatedFactoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evals': {
      id: '/_authenticated/evals'
      path: '/evals'
      fullPath: '/evals'
      preLoaderRoute: typeof AuthenticatedEvalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/digest': {
      id: '/_authenticated/digest'
      path: '/digest'
      fullPath: '/digest'
      preLoaderRoute: typeof AuthenticatedDigestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cost': {
      id: '/_authenticated/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof AuthenticatedCostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/capture': {
      id: '/_authenticated/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof AuthenticatedCaptureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/build': {
      id: '/_authenticated/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof AuthenticatedBuildRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ask': {
      id: '/_authenticated/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AuthenticatedAskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAskRoute: typeof AuthenticatedAskRoute
  AuthenticatedBuildRoute: typeof AuthenticatedBuildRoute
  AuthenticatedCaptureRoute: typeof AuthenticatedCaptureRoute
  AuthenticatedCostRoute: typeof AuthenticatedCostRoute
  AuthenticatedDigestRoute: typeof AuthenticatedDigestRoute
  AuthenticatedEvalsRoute: typeof AuthenticatedEvalsRoute
  AuthenticatedFactoryRoute: typeof AuthenticatedFactoryRoute
  AuthenticatedFilesRoute: typeof AuthenticatedFilesRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedMemoryRoute: typeof AuthenticatedMemoryRoute
  AuthenticatedModelScannerRoute: typeof AuthenticatedModelScannerRoute
  AuthenticatedModelsRoute: typeof AuthenticatedModelsRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedPromptsRoute: typeof AuthenticatedPromptsRoute
  AuthenticatedProposalsRoute: typeof AuthenticatedProposalsRoute
  AuthenticatedSkillsRoute: typeof AuthenticatedSkillsRoute
  AuthenticatedSystemRoute: typeof AuthenticatedSystemRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAskRoute: AuthenticatedAskRoute,
  AuthenticatedBuildRoute: AuthenticatedBuildRoute,
  AuthenticatedCaptureRoute: AuthenticatedCaptureRoute,
  AuthenticatedCostRoute: AuthenticatedCostRoute,
  AuthenticatedDigestRoute: AuthenticatedDigestRoute,
  AuthenticatedEvalsRoute: AuthenticatedEvalsRoute,
  AuthenticatedFactoryRoute: AuthenticatedFactoryRoute,
  AuthenticatedFilesRoute: AuthenticatedFilesRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedMemoryRoute: AuthenticatedMemoryRoute,
  AuthenticatedModelScannerRoute: AuthenticatedModelScannerRoute,
  AuthenticatedModelsRoute: AuthenticatedModelsRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedPromptsRoute: AuthenticatedPromptsRoute,
  AuthenticatedProposalsRoute: AuthenticatedProposalsRoute,
  AuthenticatedSkillsRoute: AuthenticatedSkillsRoute,
  AuthenticatedSystemRoute: AuthenticatedSystemRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ProbeOverviewRoute: ProbeOverviewRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
