/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedDigestRouteImport } from './routes/_authenticated/digest'
import { Route as AuthenticatedCaptureRouteImport } from './routes/_authenticated/capture'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDigestRoute = AuthenticatedDigestRouteImport.update({
  id: '/digest',
  path: '/digest',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaptureRoute = AuthenticatedCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture': typeof AuthenticatedCaptureRoute
  '/digest': typeof AuthenticatedDigestRoute
  '/overview': typeof AuthenticatedOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capture': typeof AuthenticatedCaptureRoute
  '/digest': typeof AuthenticatedDigestRoute
  '/overview': typeof AuthenticatedOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/capture': typeof AuthenticatedCaptureRoute
  '/_authenticated/digest': typeof AuthenticatedDigestRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/capture' | '/digest' | '/overview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/capture' | '/digest' | '/overview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/capture'
    | '/_authenticated/digest'
    | '/_authenticated/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/digest': {
      id: '/_authenticated/digest'
      path: '/digest'
      fullPath: '/digest'
      preLoaderRoute: typeof AuthenticatedDigestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/capture': {
      id: '/_authenticated/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof AuthenticatedCaptureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCaptureRoute: typeof AuthenticatedCaptureRoute
  AuthenticatedDigestRoute: typeof AuthenticatedDigestRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCaptureRoute: AuthenticatedCaptureRoute,
  AuthenticatedDigestRoute: AuthenticatedDigestRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
